name: lazydogsbus
description: "Um novo projeto Flutter para o aplicativo Lazydogsbus."
# A linha 'publish_to' impede que o pacote seja publicado no pub.dev
publish_to: 'none' 

# A versão do aplicativo e o código de build
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Adiciona a dependência para obter informações da versão do aplicativo
  package_info_plus: ^8.0.2 
  cupertino_icons: ^1.0.6 
  google_maps_flutter: ^2.5.0 
  http: ^1.2.1 # <--- ESTA É A NOVA LINHA ADICIONADA PARA A DEPENDÊNCIA HTTP

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Ferramentas de análise de código para Flutter
  flutter_lints: ^3.0.0

# Configurações específicas do Flutter
flutter:
  # Habilita o uso do Material Design para a interface do usuário
  uses-material-design: true
  assets:
    - assets/